{% set name = "pytest-datadir" %}
{% set version = "1.1.0" %}
{% set sha256 = "450e60d0c70209659d342d7de0bf0987af7a15e705339f0109de41f5bd50d080" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - setuptools_scm
  run:
    - python
    - pytest

test:
  requires:
    - pytest
  imports:
    - pytest_datadir
  commands:
    - pytest --help

about:
  home: https://github.com/gabrielcnr/pytest-datadir
  license: MIT
  summary: pytest plugin for manipulating test data directories and files.

extra:
  recipe-maintainers:
    - nicoddemus
    - gabrielcnr
    - edisongustavo
    - gqmelo
    - IgorTG
