travis:
  secure:
    BINSTAR_TOKEN: OG3N5T0tzCZSMuOU5JvMQuO75Aj23MPrMIdl4KLFukiO4ueOn53FmybqWYzQ1jTADUjy0IjT41Ikyha4RNPqEabkwtT8qcW5vY6NOtVWHcpge1nZH33kd/U+pWY1BA6JV2JloQiaT/2vJ5jJSjM1u/CCOPZLFFPAd4om+gU8l/Vgguw1C0w2uQ+jO5A3nc8MwNvIyzZXrYPskgtXaMMVkYPo98hyx7tRzgKDlevmYtJ6X62qQAWzZFPxY4PBDbRo6hNWBkd51w4uihnFFdV1kS3opZv3Jj8yLZTbem1Fz5blIBLwbLyVRrU0Ne589+vFnTKB12CA9tyLBZ9Su6+AwYeTHREpp1T5xBIezlfh18fjzs0ZqSsWy0VkG1qXhHWDVgatHtjE8oZcCi3mUTuxl6Qpsgv98cBXKScqxpY+olMJRsGe+264Avz1S3geUpLZuoUC/p1R/QLe4TeWipiBdyfX9qjby1WthEG4+k5zCzrOksniMYftY5kqQnAp4dW8M3YoopJk7re0hammCnNt7Vi4xdp7XHr4qin4zwz3c3QbSKmsAvg+tgTIfwOM4oYjSIBvBajYU7KVJx5kB9CzigXBCBky49MUXvWmOXPRzZZ4Hsdhw9kSFFOHdLvF38PG4JSD7hItwJ7XEunXStz+FfAyTCveNmp9bFAxk9Ny9Ug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
