travis:
  secure:
    BINSTAR_TOKEN: ea4zuQ0FTn+d/mZUxXfLj9vMJaLChz4JZuXhK7a65cQToO7HwQHguyRnkjbOE5EY182eblYhuxmobNqSsRYIQeYszvyNVV4otoF7GkEvUxOxY3Zg9XZcg+M8vVmri4k9PLzBscVBQOrcjDiwqeQqUNfM/Ht2FEQ7FwM+2I69UthvhiDVMNaGs8eXEVhCYGuf9wRqv9wj5wFDKpwvsij0ionBaeD6To5xxDaNTGdO0XKE3GsPKsIZz6h25UanAXSqSGHXaHare0l/qU0m3rTVmnu0fU8ja17xaBN6JcW2yzrHULtSM3AbK2ZeM3VTY3zJcCmZVHdo9UGeYO1Bp/VC1EU9SCtUalYm22q0iiyPH7OPlIJGg2zU+fgoRMiQvSNXf9WKb2gXqXS7LiY5+s+wOpb9Bae5y3AVpoGh4UMAb14GgV6Eze62D4SIHxjkhRqQ7k5c3/dvQyv2JskQgjqyTV+/xnFGpfE1Bl/wG5LawlkiBbBwmM/RyZokRMUheIUeRVOvYfJQdX8Y4PKgY7ctdziEHrYAKo/zzVjbSX635lbrAPXCO2imuwDWpmjzL31Yzp9Aie3EBfkC4Odu8rwSOh+wUJGDKb/lxb+kMAYh7hckrBlelGsMzqs+OTopnmONmp5YLoTFOrScgYvBFxIFZy13rbiieHojhA1TUUTPO5c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
